config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  resources :authors, only: [:show]

  get '*path' => redirect('/')
  resources :taggings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :authors, through: :taggings, dependent: :destroy

  def author_list
    list = []
    authors.each {|a| list.push(a.name)}
    list.join(", ")
  end
  def author_list=(author_str)
    list = author_str.split(", ")
    uniqs = list.map {|a| a.strip.capitalize}.uniq

    cleans = uniqs.map {|a| Author.find_or_create_by(name: a)}
    self.authors = cleans
  end
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :author
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
    @articles = Article.all
    @comment = Comment.new
    @comment.article_id = @article_id
  end

  def new
    @article = Article.new
    @articles = Article.all
  end

  def edit
    @articles = Article.all
  end

  def create
    @article = Article.new(article_params)
    @article.original = params[:article][:body]
    author_list = article_params[:signature]
    @article.author_list += ", " + author_list
    
    @articles = Article.all

    if @article.title == '' || @article.body == '' || @article.signature == ''
      flash.now.notice = "All fields must contain text!"
      render :new
      return
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article}
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @articles = Article.all
    
    if params[:article][:title] == '' || params[:article][:body] == '' || params[:article][:signature] == ''
      flash.now.notice = "All fields must contain text!"
      render :edit
      return
    end

    author_list = article_params[:signature]
    @article.author_list += ", " + author_list

    origin = Article.find(params[:id])
    params[:article][:signature] = origin.signature
    @article.update(article_params)

    redirect_to @article
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_path }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :signature, :author_list)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    #@authors = Author.all
    redirect_to articles_path
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
    @articles = Article.all
  end

  # GET /authors/new
  def new
    #@author = Author.new
    redirect_to articles_path
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    if @comment.user == '' || @comment.body == ''
      respond_to do |format|
        format.html { redirect_to article_path(@comment.article), notice: 'Fields cannot be empty!' }
      end
      return
    end
    @comment.save
    redirect_to article_path(@comment.article)
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to article_path(@comment.article), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user, :body, :article_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/articles/_column.html.erb
<div class="columns">
  <% if locale[:side] == "left" %>
    <div class="main_page_link"><%= link_to 'Main Page', articles_path unless article == nil %></div>
  <% elsif locale[:side] == "right" %>
    <div class="main_page_link"><%= link_to "WRITE NEW ARTICLE!", new_article_path unless article == nil %></div>
  <%end%>
  <% article = @articles[rand(@articles.length-1)] unless article == nil %>
  <div class="articlebox" id=<%= article_path(article) unless article == nil %> >
    <h2 class="showtitle"><%= article.title unless article == nil %></h2>
    <p class="showbody"><%= article.body unless article == nil %></p>
    
  </div>
  <% article = @articles[rand(@articles.length-1)] unless article == nil %>
  <div class="articlebox" id=<%= article_path(article) unless article == nil %> >
    <h2 class="showtitle"><%= article.title unless article == nil %></h2>
    <p class="showbody"><%= article.body unless article == nil %></p>
  </div>
</div>

app/views/articles/_disp.html.erb
<h2 class="showtitle"><%= article.title unless article == nil %></h2>
<% if request.original_url.include?("recall=true") %>
  <div class="showbody"><%= simple_format(article.original) unless article == nil %></div>
<% else %>
  <div class="showbody"><%= simple_format(article.body) unless article == nil %></div>
<% end %>
<p class="showsignature">Created by: <%= link_to article.signature, author_path(Author.find_or_create_by(name: article.signature)) unless article == nil %> (<%= link_to "Original", article_path(:id => article.id, :recall => true) unless article == nil  %>)</p>
<p class="showtime">Created at: <%= article.created_at_was.strftime("%d %B %Y") unless article == nil %></p>
<p class="showsignature">Edited by: <% unless article == nil %><% article.authors.each do |author| %> <%= link_to author.name, author_path(author) %> <% end %><% end %></p>
<div class="main_page_link"><%= link_to 'Edit This Article', edit_article_path(article) unless article == nil %></div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new_article_label"><%= form.label :title %></div>
  <div class="new_input"><%= form.text_field :title %></div>

  <div class="new_article_label"><%= form.label :body %></div>
  <div class="new_body"><%= form.text_area :body %></div>

  <%= notice %>
  <div class="new_article_label">Created by</div>
  <div class="new_input"><%= form.text_field :signature %></div>

  <div class="new_submit"><%= form.submit %></div>
<% end %>

app/views/articles/_list.html.erb
<div class="articlelist">
  <h2 class="showtitle">All articles</h2>
  <ul>
  <% @articles.reverse_each do |article| %>
    <li class="navlinks"><%= link_to article.title, article %> (<%= link_to article.signature, author_path(Author.find_or_create_by(name: article.signature)) %>)
    <%#= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
  </ul>
  <h3 class="new_article_link"><%= link_to "WRITE NEW ARTICLE NOW!", new_article_path %></h3>
</div>

app/views/articles/edit.html.erb
<%= render 'column', article: @articles, locale: {side: "left"} %>

<div class = "new_article_form">
  <h1>Edit Article</h1>

  <%= render 'form', article: @article %>

  <div class="linkto"><%= link_to 'Show', @article %></div>
  <div class="linkto"><%= link_to 'Main Page', articles_path %></div>
</div>

<%= render 'column', article: @articles, locale: {side: "right"} %>

app/views/articles/index.html.erb
<%= render 'column', article: @articles, locale: {side: "left"} %>

<div class="main">
  <div class="welcome">Welcome to my blog, feel free to contribute!</div>
    <div class="latestarticle">
      <h1 class="latesttitle">Latest Article</h1>
      <%= render 'disp', article: @articles[@articles.length-1] %>
    </div>
    <%= render 'list' %>
</div>

<%= render 'column', article: @articles, locale: {side: "right"} %>

app/views/articles/new.html.erb
<%= render 'column', article: @articles, locale: {side: "left"} %>

<div class = "new_article_form">
  <h1>New Article</h1>

  <%= render 'form', article: @article %>

  <div class="linkto"><%= link_to 'Back', articles_path %></div>

  <div class="flash"><%#= flash.notice %></div>
</div>

<%= render 'column', article: @articles, locale: {side: "right"} %>

app/views/articles/show.html.erb
<%= render 'column', article: @articles, locale: {side: "left"} %>

<div class="main">
  <div class="welcome">Welcome to my blog, feel free to contribute!</div>
    <div class="latestarticle">
      <%= render 'disp', article: @article %>
    </div>
    
    <% if @article.comments.length != 0 %>
    <div class="commentbox">
      <h2>Comments</h2>
      <%= render partial: "comments/comment", collection: @article.comments %>
    </div>
    <% end %>
    <div class="commentbox"><%= render partial: "comments/form" %></div>

    <%= render 'list' %>
</div>

<%= render 'column', article: @articles, locale: {side: "right"} %>

app/views/authors/show.html.erb
<%= render 'articles/column', article: @articles, locale: {side: "left"} %>

<div class="main">
  <div class="welcome">Welcome to my blog, feel free to contribute!</div>
    <div class="latestarticle">
        <h2 class="showtitle">Author Name: <%= @author.name %></h2>
        <div class="outlisting">
        <div class="listing">
        <h3 class="top-margin-10px">Contributions</h3>
        <ul>
        <% @author.articles.each do |article| %>
          <li class="navlinks"><%= link_to article.title, article_path(article) %></li>
        <% end %>
        </ul>
        </div>
        </div>
    </div>

    <%= render 'articles/list' %>
    <div class="main_page_link"><%= link_to 'Main Page', articles_path %></div>
</div>

<%= render 'articles/column', article: @articles, locale: {side: "right"} %>

app/views/comments/_comment.html.erb
<div class="eachcomment">
<label class="comment_user"><%= comment.user %>:</label>
<label class="comment_body"><%= comment.body %></label>
<%#= link_to 'Destroy', article_comment_path(comment.article.id, comment.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
</div>
<br/>

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="new_article_label">Your name</div>
  <div class="new_input"><%= form.text_field :user, :maxlength => 20 %>
  </div>

  <div class="new_article_label">Your comment</div>
  <div class="new_comment"><%= form.text_area :body, :maxlength => 200 %></div>

  <div class="new_submit"><%= form.submit %></div>
  <%= notice %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>